# Generated by Django 2.0.5 on 2018-05-22 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('initialapp', '0002_auto_20180522_1324'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Collection',
        ),
    ]
