# Generated by Django 2.0.5 on 2018-05-23 15:20

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initialapp', '0003_delete_collection'),
    ]

    operations = [
        migrations.CreateModel(
            name='rsvp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('note', ckeditor.fields.RichTextField(blank=True)),
            ],
        ),
    ]
