# Generated by Django 2.0.5 on 2018-05-24 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('initialapp', '0005_language'),
    ]

    operations = [
        migrations.DeleteModel(
            name='language',
        ),
    ]
